# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  host: <%= ENV["DATABASE_HOST"] %>
  port: 3306
  database: <%= ENV["DATABASE_NAME"] %>
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  socket: /tmp/mysql.sock
  timeout: 5000
  pool: 5

development:
  <<: *default
  
